version: "3"
services:
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      app-network:
        aliases:
          - db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    container_name: app
    restart: unless-stopped
    build: .
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      app-network:
        aliases:
          - app
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/. local/dev-env.sh && node lib/index.js
    links:
      - db
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
