version: "3"
services:
  mongo:
    image: mongo:4.1.8-xenial
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    container_name: app
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh mongo:27017 -- /home/node/app/node_modules/.bin/. local/dev-env.sh && node lib/index.js
    links:
      - mongo
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
